kind: Deployment
apiVersion: apps/v1
metadata:
  name: veldeploy


spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev

  template:
    metadata:
      name: velpod
      labels:
        env: dev


    spec:
      containers:
        - name: vel-1
          image: sudarshan1896/my:1.0
          ports:
            - containerPort: 8081

